import ClickEvent from './clickModel.js';
import Deal from '../deals/dealModel.js';
import AdminSettings from '../admin/adminSettingsModel.js';
import { detectMerchant, appendSubid, ensureAmazonTag, wrapCuelinks } from './subidBuilder.js';

/**
 * Build the subid string we attach to outgoing affiliate URLs.
 *
 * Prefix "cr_" is the Chingiringi marker — easy to grep in merchant reports
 * and lets us tell our subids apart from clicks generated by other publishers
 * who happen to share the same affiliate network.
 */
function buildSubid(userId) {
  if (userId) return `cr_${userId}`;
  // Anonymous click — timestamp suffix keeps subids unique per click for the
  // rare case that merchant reports return identical anon rows.
  return `cr_anon_${Date.now()}`;
}

/**
 * POST /api/clicks/log
 *
 * Called from the app right before opening an affiliate URL. Returns the
 * subid-rewritten URL plus the clickId for later correlation. Auth is
 * optional — anonymous clicks log too, just with an anon subid.
 *
 * Body: { dealId?, productId?, url?, source? }
 *   - dealId: preferred; we resolve affiliateUrl from the deal
 *   - url: explicit override for ad-hoc clicks not tied to a deal
 *   - source: where in the app the click came from (analytics)
 *
 * Returns: { clickId, redirectUrl }
 */
export const logClick = async (req, res) => {
  const { dealId, productId, url: explicitUrl, source = 'unknown' } = req.body;

  let originalUrl = explicitUrl;
  let dealDoc = null;
  if (dealId) {
    dealDoc = await Deal.findById(dealId).select('affiliateUrl brand viaCuelinks').lean();
    if (!dealDoc) {
      res.status(404);
      throw new Error('Deal not found');
    }
    originalUrl = dealDoc.affiliateUrl;
  }
  if (!originalUrl) {
    res.status(400);
    throw new Error('Either dealId or url is required');
  }

  // Load coin-economy + merchant credentials. Used for URL wrapping below.
  const settings = await AdminSettings.get();

  // ── URL prep pipeline ──────────────────────────────────────────────
  // Order matters: Amazon tag applies to the raw merchant URL. Then Cuelinks
  // wrapping (if applicable) encodes the tagged URL. Finally subid appends
  // to whatever URL the user ends up hitting.
  let preparedUrl = originalUrl;
  const rawMerchant = detectMerchant(preparedUrl);
  if (rawMerchant === 'amazon' && settings.amazonAssociateTag) {
    preparedUrl = ensureAmazonTag(preparedUrl, settings.amazonAssociateTag);
  }
  if (dealDoc?.viaCuelinks && settings.cuelinksPublisherId) {
    preparedUrl = wrapCuelinks(preparedUrl, settings.cuelinksPublisherId);
  }

  const userId = req.user?._id?.toString();
  const subid = buildSubid(userId);
  const merchant = detectMerchant(preparedUrl); // may now be 'cuelinks' if wrapped
  const redirectedTo = appendSubid(preparedUrl, subid, merchant);

  const click = await ClickEvent.create({
    userId:    userId || undefined,
    dealId:    dealId || undefined,
    productId: productId || undefined,
    merchant,
    source,
    originalUrl,
    redirectedTo,
    subid,
    ip:        req.ip,
    userAgent: req.headers['user-agent'],
    referer:   req.headers.referer || req.headers.referrer,
  });

  // Bump legacy deal counter (fire-and-forget — we never want this to block
  // the redirect, and a failed counter increment is not a user-visible bug).
  if (dealId) {
    Deal.findByIdAndUpdate(dealId, { $inc: { clickCount: 1 } }).catch(() => {});
  }

  res.status(200).json({
    status: 'success',
    data: { clickId: click._id, redirectUrl: redirectedTo },
  });
};

/**
 * GET /api/clicks/redirect?dealId=...&source=...
 *
 * Server-side 302 with logging. Use for share links, email links, QR codes —
 * places where the app can't pre-call /log. Same auth treatment (anonymous OK).
 */
export const redirectAndLog = async (req, res) => {
  const { dealId, source = 'redirect' } = req.query;
  if (!dealId) {
    res.status(400);
    throw new Error('dealId required');
  }
  const deal = await Deal.findById(dealId).select('affiliateUrl viaCuelinks').lean();
  if (!deal) {
    res.status(404);
    throw new Error('Deal not found');
  }

  const settings = await AdminSettings.get();
  let preparedUrl = deal.affiliateUrl;
  const rawMerchant = detectMerchant(preparedUrl);
  if (rawMerchant === 'amazon' && settings.amazonAssociateTag) {
    preparedUrl = ensureAmazonTag(preparedUrl, settings.amazonAssociateTag);
  }
  if (deal.viaCuelinks && settings.cuelinksPublisherId) {
    preparedUrl = wrapCuelinks(preparedUrl, settings.cuelinksPublisherId);
  }

  const userId = req.user?._id?.toString();
  const subid = buildSubid(userId);
  const merchant = detectMerchant(preparedUrl);
  const redirectedTo = appendSubid(preparedUrl, subid, merchant);

  // Fire-and-forget log — never block the user's redirect on DB write.
  ClickEvent.create({
    userId: userId || undefined,
    dealId,
    merchant,
    source,
    originalUrl: deal.affiliateUrl,
    redirectedTo,
    subid,
    ip:        req.ip,
    userAgent: req.headers['user-agent'],
    referer:   req.headers.referer || req.headers.referrer,
  }).catch(() => {});

  Deal.findByIdAndUpdate(dealId, { $inc: { clickCount: 1 } }).catch(() => {});

  res.redirect(302, redirectedTo);
};

/**
 * GET /api/clicks/user/:userId
 *
 * Admin-only. Returns a user's click history newest-first, used by the
 * upcoming User Wallet timeline view (clicks interleaved with transactions).
 */
export const getUserClicks = async (req, res) => {
  const { userId } = req.params;
  const { limit = 50, since } = req.query;

  const filter = { userId };
  if (since) filter.createdAt = { $gte: new Date(since) };

  const clicks = await ClickEvent.find(filter)
    .sort({ createdAt: -1 })
    .limit(Math.min(Number(limit) || 50, 200))
    .populate('dealId', 'title brand affiliateUrl')
    .lean();

  res.json({ status: 'success', data: { clicks } });
};
